name: env_var
on:
 push:
    branches: [test_CI]
 workflow_dispatch:
jobs:
  display:
    runs-on: windows-latest
    env:
     API_KEY: XXXXXXXX
    steps:
      - name: Display custom environment variables
        run: |
          echo "The platform is ${{env.API_KEY}}"
          echo "the region is $API_KEY"
  
 
